"""Step 2 — Parsing and Cleaning."""
import streamlit as st
from ui import (render_topbar, render_step_header, render_thinking_card,
                render_what_we_built, render_enterprise_note, render_risk_table, render_nav)

RAW_INPUT = """\
RESULTS — Open Domain QA Performance

RAG combines parametric memory with non-parametric retrieval,
allowing it to access knowledge without storing it in model weights.

Table 1: Benchmark Results on NaturalQuestions

| Model        | Exact Match | F1    |
|--------------|-------------|-------|
| T5-11B       | 34.5        | 45.1  |
| RAG-Sequence | 44.5        | 56.8  |
| RAG-Token    | 45.5        | 56.8  |

[Figure 2: Retrieval recall vs answer accuracy scatter plot.
Shows positive correlation between retrieval recall (x-axis)
and downstream QA accuracy (y-axis) across 5 datasets.]

See also: Lewis et al. [1], Karpukhin et al. [2], Guu et al. [3]
"""

SIMPLE_OUTPUT = """\
RESULTS Open Domain QA Performance RAG combines
parametric memory with non-parametric retrieval
allowing it to access knowledge without storing
it in model weights. Table 1 Benchmark Results
on NaturalQuestions Model Exact Match F1 T5-11B
34.5 45.1 RAG-Sequence 44.5 56.8 RAG-Token 45.5
56.8 Figure 2 Retrieval recall vs answer accuracy
scatter plot Shows positive correlation between
retrieval recall x-axis and downstream QA
accuracy y-axis across 5 datasets See also
Lewis et al 1 Karpukhin et al 2 Guu et al 3
"""

ENTERPRISE_PROSE = """\
RAG combines parametric memory with
non-parametric retrieval, allowing it
to access knowledge without storing
it in model weights.

[section="Results", type="prose",
 has_citations=false]
"""

ENTERPRISE_TABLE = """\
{
  "type": "table",
  "caption": "Benchmark Results — NaturalQuestions",
  "headers": ["Model", "Exact Match", "F1"],
  "rows": [
    ["T5-11B",       "34.5", "45.1"],
    ["RAG-Sequence", "44.5", "56.8"],
    ["RAG-Token",    "45.5", "56.8"]
  ],
  "chunk_separately": true
}
"""

ENTERPRISE_IMAGE = """\
[type: figure | id: fig_2]
Caption: "Retrieval recall vs answer
accuracy scatter plot"

Description: Positive correlation between
retrieval recall (x-axis) and downstream
QA accuracy (y-axis) across 5 datasets.

Alt-text generated by vision model
and embedded as separate chunk.
"""

RISKS = [
    {"risk": "Table flattening", "example": "Financial report table converted to unstructured text — LLM can't reason over it correctly", "mitigation": "AWS Textract and Azure Document Intelligence preserve table structure as JSON — chunk tables separately"},
    {"risk": "Code treated as prose", "example": "Python function chunked mid-logic — retrieved chunk is half a function, syntactically invalid", "mitigation": "AST-aware chunking — split at function and class boundaries, never mid-statement"},
    {"risk": "Citation noise", "example": "'[Lewis et al., 2020]' appears 47 times — dominates embedding space", "mitigation": "Strip inline citations before embedding, preserve in metadata for source attribution"},
    {"risk": "PII surviving cleaning", "example": "Customer support tickets contain names and emails — bake into vectors", "mitigation": "AWS Comprehend or Microsoft Presidio scan every chunk post-cleaning"},
]

def render():
    render_topbar()
    render_step_header("✂️", "Parsing + Cleaning",
        "Raw text is messy. Before chunking, it needs to be structured and cleaned.")

    render_thinking_card(
        "Enterprise parsing isn't about how much to strip — it's about structure preservation and content routing. "
        "Each content type (prose, table, image, code) needs a different processor. "
        "A naive loader flattens everything into one blob. "
        "A proper parser routes each block to the right specialist, then runs quality and compliance checks "
        "before anything reaches the chunker.",
        pipeline="offline"
    )

    # ── Raw input ─────────────────────────────────────────────────────────────
    st.markdown("**Raw PDF input — prose, table, and figure all mixed together:**")
    st.code(RAW_INPUT, language=None)
    st.caption("One document section containing three distinct content types. A naive loader treats this as one undifferentiated blob of text.")

    st.markdown("**What each parser does with it:**")
    col_simple, col_arrow, col_enterprise = st.columns([5, 1, 5])

    with col_simple:
        st.markdown("""
<div style="background:#FCEBEB;border:0.5px solid #F7C1C1;border-radius:8px;
padding:10px 14px;margin-bottom:8px;font-size:12px;font-weight:600;color:#501313">
⚠️ Simple parser (naive text loader)
</div>
""", unsafe_allow_html=True)
        st.code(SIMPLE_OUTPUT, language=None)
        st.caption("Table structure lost. Image reduced to caption text. Citations merged into prose. The LLM receives one undifferentiated blob — it cannot reason over the table as data.")

    with col_arrow:
        st.markdown("<div style='text-align:center;font-size:24px;padding-top:80px;color:var(--color-text-tertiary)'>vs</div>", unsafe_allow_html=True)

    with col_enterprise:
        st.markdown("""
<div style="background:#E1F5EE;border:0.5px solid #0F6E56;border-radius:8px;
padding:10px 14px;margin-bottom:8px;font-size:12px;font-weight:600;color:#085041">
✅ Enterprise parser (AWS Textract / Azure Document Intelligence)
</div>
""", unsafe_allow_html=True)

        st.markdown("<div style='font-size:11px;font-weight:600;color:var(--color-text-secondary);margin-bottom:2px'>📝 Prose — clean, cited separately</div>", unsafe_allow_html=True)
        st.code(ENTERPRISE_PROSE, language=None)

        st.markdown("<div style='font-size:11px;font-weight:600;color:var(--color-text-secondary);margin-bottom:2px'>📊 Table — preserved as structured data</div>", unsafe_allow_html=True)
        st.code(ENTERPRISE_TABLE, language="json")

        st.markdown("<div style='font-size:11px;font-weight:600;color:var(--color-text-secondary);margin-bottom:2px'>🖼️ Image — described, not discarded</div>", unsafe_allow_html=True)
        st.code(ENTERPRISE_IMAGE, language=None)

        st.caption("Three separate typed chunks. Table is queryable as structured data. Image is embedded via vision-generated description. Each chunk gets precise metadata.")

    st.markdown("---")
    st.markdown("**How enterprise parsing pipelines actually work — 4 stages:**")

    stages = [
        {
            "num": "1",
            "title": "Document Intelligence",
            "color": "#4A90D9",
            "bg": "#EBF4FD",
            "border": "#B5D4F4",
            "tools": "AWS Textract · Azure Document Intelligence · Unstructured.io",
            "bullets": [
                "Detects content types: prose, tables, figures, code, headers",
                "OCR for scanned and image-based PDFs",
                "Outputs <strong>typed blocks</strong> — not raw text",
            ],
        },
        {
            "num": "2",
            "title": "Content Router",
            "color": "#9B59B6",
            "bg": "#F5EEFB",
            "border": "#D7BEF0",
            "tools": "LangChain · LlamaIndex · custom routing logic",
            "bullets": [
                "📝 Prose → text cleaner (strip citations, normalize whitespace)",
                "📊 Table → structured extractor (preserve as JSON, keep headers + rows)",
                "🖼️ Image → vision model (generate text description for embedding)",
                "💻 Code → AST-aware parser (preserve syntax, detect language)",
            ],
        },
        {
            "num": "3",
            "title": "Quality & Compliance",
            "color": "#E67E22",
            "bg": "#FEF5EC",
            "border": "#FAD7A0",
            "tools": "Microsoft Presidio · AWS Comprehend · custom scorers",
            "bullets": [
                "PII scan — names, emails, IDs removed or redacted",
                "Language detection — flag non-target-language chunks",
                "Quality score — readability, completeness, minimum length gate",
                "Duplicate detection — hash-based dedup before any chunk reaches the index",
            ],
        },
        {
            "num": "4",
            "title": "Metadata Enrichment",
            "color": "#0F6E56",
            "bg": "#E1F5EE",
            "border": "#A5D6C7",
            "tools": "LLM classifiers · NER models · ACL propagation",
            "bullets": [
                "Auto-tag: document type, section, has_code / has_tables / has_citations",
                "Entity extraction: named entities, dates, product names",
                "ACL propagation: permissions inherited from source document",
                "Freshness stamps: created_at, updated_at written at ingestion time",
            ],
        },
    ]

    cols = st.columns(4)
    for col, stage in zip(cols, stages):
        with col:
            bullets_html = "".join(
                f"<li style='margin-bottom:4px'>{b}</li>" for b in stage["bullets"]
            )
            st.markdown(
                f"<div style='background:{stage['bg']};border:0.5px solid {stage['border']};"
                f"border-radius:8px;padding:12px;height:100%'>"
                f"<div style='font-size:18px;font-weight:700;color:{stage['color']}'>{stage['num']}</div>"
                f"<div style='font-size:12px;font-weight:600;color:{stage['color']};margin:4px 0 6px'>"
                f"{stage['title']}</div>"
                f"<div style='font-size:10px;color:#555;margin-bottom:8px;font-style:italic'>"
                f"{stage['tools']}</div>"
                f"<ul style='font-size:11px;color:#2d2d2d;line-height:1.6;"
                f"padding-left:14px;margin:0'>{bullets_html}</ul>"
                f"</div>",
                unsafe_allow_html=True,
            )

    st.markdown("---")
    st.markdown("**Metadata extracted per chunk:**")
    st.code("""{
  "source": "Lewis et al. RAG Paper (arXiv:2005.11401)",
  "document_type": "research_paper",
  "section": "Results — Open Domain QA",
  "has_code": false,
  "has_tables": true,
  "has_citations": true,
  "chunk_position": "middle",
  "word_count": 187,
  "embedding_model": "tfidf_v1",
  "chunking_strategy": "fixed_token_overlap",
  "indexed_at": "2024-05-01T09:23:41Z"
}""", language="json")
    st.caption("This metadata enables filtering at retrieval time — without it, retrieval is blind.")

    render_what_we_built(
        "We apply basic cleaning — strip HTML, normalize whitespace, extract structural markers. "
        "In production, this is a 4-stage pipeline: document intelligence to detect content types, "
        "a content router to send each type to the right processor, a quality and compliance layer "
        "(PII, deduplication, language detection), and metadata enrichment. "
        "We simplify here so the focus stays on what happens to clean, structured text downstream: "
        "chunking, metadata tagging, embedding, and retrieval."
    )
    render_enterprise_note(
        "Enterprises run dedicated document intelligence pipelines before any text reaches the RAG system. "
        "AWS Textract extracts structured text, tables, and forms from PDFs including scanned documents. "
        "Azure Document Intelligence handles invoices, receipts, contracts — preserving table structure as JSON. "
        "Cleaning pipelines run quality scoring on every chunk — readability score, language detection, "
        "PII scan, duplicate detection. Chunks below quality threshold are quarantined for human review."
    )
    render_risk_table(RISKS)
    render_nav(next_label="Next: Chunking →", pipeline="offline")
